Update faq.yaml
fab-geocommuns/RNB-site pull request #110
Opened 2024-05-02 08:04 UTC by AudreyH49

Modifications apportées : 
- Ajout d'une balise bold, pour la question "Comment consulter, télécharger, alimenter et/ou intégrer les données du RNB à vos systèmes métiers ?" (sinon tout était en gras)
- sur cette question : ajout des URL github et faire un signalement batiment
- Ajout des URL également sur la réponse à la question "Que faire si je constate une erreur dans le Référentiel National des Bâtiments ?"
- Ajout d'un espace à la réponse "Est ce que les identifiants du RNB sont pérennes ?"

PR pour @pauletienney

2024-05-06 13:59 UTC, pauletienney requested changes
Il y a quelques balises mal fermées. Je les ai commentées.

2024-05-07 15:39 UTC, AudreyH49 reviewed
@pauletienney

2024-07-10 07:57 UTC, bbaret commented
Déjà corrigé dans la #131

2024-07-10 07:57 UTC, bbaret commented
Déjà corrigé dans la #131

2024-07-10 07:57 UTC, closed without merging