Ajout du bouton de sélection du style d'affichage des bâtiments (point ou emprise au sol)
fab-geocommuns/RNB-site pull request #171
Opened 2024-10-14 07:21 UTC by bbaret

2024-10-14 07:26 UTC, bbaret commented
Avec les points:
<img width="595" alt="image" src="https://github.com/user-attachments/assets/61694913-c883-4cba-b77b-61e3f8011672">

Avec les emprises:
<img width="575" alt="image" src="https://github.com/user-attachments/assets/a2335d00-6bf2-44ee-83b2-e06668795b30">

2024-10-15 15:56 UTC, pauletienney requested changes
C'est excellent d'avoir enfin l'affichage des polygones !
Le seul problème que j'ai est à propos de l'icone. On présente par défaut un point sans libellé et il quasiment assuré que les utilisateurs ne le voient pas ou ne comprenne pas de quoi il s'agit.
Est-ce que tu penses qu'on pourrait changer le controle pour que celui-ci soit plus explicite ?

2024-10-15 16:01 UTC, pauletienney submitted a review, later dismissed
Un bug sur la vue aérienne, j'ai commenté le fichier que je pense concerné

2024-10-15 16:01 UTC, pauletienney commented on components/map/MapStyleSwitcher.ts
Il y a un bug, probablement lié à ce fichier : quand on passe en choisit l'affichage des bâtiment en polygones puis qu'on passe en vue aérienne, les polygones disparaissent.

2024-10-18 08:28 UTC, pauletienney commented on components/map/BuildingSourceSwitcherControl.ts
> +      this._text.textContent = this._isShapesSource ? 'Point' : 'Emprise';
Je crains que le terme "Emprise" provoque des discussions d'experts. De ce que j'en sais la BD Topo se base plutôt sur les toits pour dessiner les bâtiments alors que la DGFiP se base sur l'emprise. Lyon se base sur les pans de toits, etc. C'est un vrai sujet pour eux et je pense qu'il serait mieux d'éviter ce genre de considérations. 

Je pense que "Polygones" à la place d'"Emprise" serait plus neutre.

-----

Egalement à propos de l'affichage de ce texte, je pense qu'on devrait rester sur le même fonctionnement que Plan / Satellite : on affiche le libellé (et l'icone) de l'action qui sera activée après le clic. Un peu comme un player audio qui affiche l'icone Pause que le son joue et Play quand c'est en pause.

Qu'en dis tu ?

2024-10-18 09:01 UTC, bbaret commented on components/map/BuildingSourceSwitcherControl.ts
> +      this._text.textContent = this._isShapesSource ? 'Point' : 'Emprise';
Ca me va et effectivement c'est plus logique :)

2024-10-23 09:42 UTC, merged