Correction de l'authentification et ajout de la désactivation d'un bâtiment
fab-geocommuns/RNB-site pull request #185
Opened 2024-11-04 09:25 UTC by bbaret

2024-11-13 09:50 UTC, fchabouis commented on components/contribution/DisableBuilding.tsx
> +          title={`Désactiver le bâtiment ${selectedItem.rnb_id}`}
Est-ce qu'on peut parler de désactiver le RNB ID XXX plutôt ?

2024-11-13 09:54 UTC, fchabouis commented on components/contribution/DisableBuilding.tsx
> +            description={`L'action que vous vous apprêtez à effectuer ne supprime pas définitivement le bâtiment. Il est seulement désactivé et son accès restera possible afin de garder un RNB ID pér
```suggestion
            description={`L'action que vous vous apprêtez à effectuer ne supprime pas le RNB ID du référentiel. Il va être désactivé et sa consultation restera possible.`}
```

2024-11-13 09:56 UTC, fchabouis commented
Je n'ai pas réussi à me connecter dans la preview, on fait comment ? (question de newbie ahah)

2024-11-22 15:51 UTC, pauletienney requested changes
Quelques remarques fonctionnelles : 

- [ ] le background sombre à l'ouverture de la modal a un comportement étrange. Il change de couleur en fonction d'où se trouve le curseur
- [ ] le champs de recherche a un z-index plus élevé que ce background sombre. Sur écran de d'ordi portable, il mord sur le message de la modal
- [ ] format modal : est-ce que c'est le format qu'on doit utiliser ? Consulter la carte peut avoir son utilité quand on édite un bâtiment. Est-ce que ne remettrait pas l'ensemble des outils dans le panneau latéral (message de confirmation, message de validation, etc)
- [ ] consultation d'un bâtiment désactivé : le panneau latéral devrait indiquer clairement que nous sommes en train de consulter un bâtiment/identifiant désactivé (besoin de mettre un lien/explication sur ce qu'est un bâtiment/identifiant désactivé ?). Aussi question pas évidente : doit on montrer la shape/point d'un bâtiment désactivé qu'on consulte ? Ca pourrait avoir son utilité pour voir où il se trouvait (par exemple par dessus un bosquet)

2024-12-12 08:07 UTC, merged